"""Stress test: MLX-Tinker vs Tinker API training equivalence.

Compares local mlx-tinker training against golden reference logs
generated by scripts/generate_reference_logs.py via the Tinker API.

The reference logs are committed at tests/fixtures/tinker_reference_logs.json.
This test runs the same data locally and compares loss curves.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from tests.stress.conftest import skip_insufficient_ram

pytestmark = [pytest.mark.stress, skip_insufficient_ram]

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"
REFERENCE_FILE = FIXTURES_DIR / "tinker_reference_logs.json"


def _load_reference_logs():
    if not REFERENCE_FILE.exists():
        pytest.fail(
            f"Reference logs not found at {REFERENCE_FILE}. "
            "Run `python scripts/generate_reference_logs.py` first."
        )
    with open(REFERENCE_FILE) as f:
        return json.load(f)


def _reference_step_loss(step: dict) -> float:
    """Return the normalized loss value for a reference-log step."""
    if "loss_mean" in step:
        return float(step["loss_mean"])
    if "loss_sum" in step:
        n_tokens = max(int(step.get("n_tokens", 0)), 1)
        return float(step["loss_sum"]) / n_tokens
    return float(step["loss"])


class TestTinkerMLXEquivalence:
    """Compare mlx-tinker training vs Tinker API golden reference."""

    def test_sft_loss_curve_correlation(self, model_name):
        """SFT loss curves should be correlated (Pearson r > 0.90)."""
        ref = _load_reference_logs()
        ref_losses = np.array([_reference_step_loss(s) for s in ref["sft_steps"]])

        # Run local SFT with same data
        local_losses = self._run_local_sft(model_name, ref)

        if len(local_losses) < 2 or len(ref_losses) < 2:
            pytest.fail("Not enough steps for correlation")

        min_len = min(len(local_losses), len(ref_losses))
        correlation = np.corrcoef(ref_losses[:min_len], local_losses[:min_len])[0, 1]

        print("\n=== Tinker vs MLX SFT Correlation ===")
        print(f"  Ref losses:   {ref_losses[:5].round(4).tolist()}...")
        print(f"  Local losses: {np.array(local_losses[:5]).round(4).tolist()}...")
        print(f"  Correlation:  {correlation:.4f}")

        assert correlation > 0.90, f"SFT loss correlation {correlation:.4f} < 0.90"

    def test_sft_initial_loss_close(self, model_name):
        """Step 0 loss should be close (< 15% relative diff) — same model, same data."""
        ref = _load_reference_logs()
        ref_loss_0 = _reference_step_loss(ref["sft_steps"][0])

        local_losses = self._run_local_sft(model_name, ref, n_steps=1)
        local_loss_0 = local_losses[0]

        rel_diff = abs(ref_loss_0 - local_loss_0) / (abs(ref_loss_0) + 1e-8)
        print("\n=== Initial Loss Comparison ===")
        print(f"  Tinker: {ref_loss_0:.4f}, MLX: {local_loss_0:.4f}, rel_diff: {rel_diff:.4f}")

        assert rel_diff < 0.15, f"Initial loss rel_diff {rel_diff:.4f} > 0.15"

    def test_sft_per_step_loss_close(self, model_name):
        """Per-step losses should be within 20% relative difference."""
        ref = _load_reference_logs()
        ref_losses = np.array([_reference_step_loss(s) for s in ref["sft_steps"][:10]])

        local_losses = np.array(self._run_local_sft(model_name, ref, n_steps=10))

        min_len = min(len(ref_losses), len(local_losses))
        rel_diffs = np.abs(ref_losses[:min_len] - local_losses[:min_len]) / (
            np.abs(ref_losses[:min_len]) + 1e-8
        )
        max_rel_diff = rel_diffs.max()

        print("\n=== Per-Step Loss Comparison ===")
        print(f"  Max relative diff: {max_rel_diff:.4f}")
        print(f"  Mean relative diff: {rel_diffs.mean():.4f}")

        # Loose tolerance: different hardware (GPU vs Apple Silicon), quantization
        assert max_rel_diff < 0.20, f"Max per-step rel_diff {max_rel_diff:.4f} > 0.20"

    def test_rl_loss_direction_matches(self, model_name):
        """Both RL loss curves should trend in the same direction."""
        ref = _load_reference_logs()
        if len(ref.get("rl_steps", [])) < 2:
            pytest.fail("Not enough RL steps in reference")

        ref_losses = np.array([_reference_step_loss(s) for s in ref["rl_steps"]])
        ref_trend = ref_losses[-1] - ref_losses[0]

        local_losses = np.array(self._run_local_rl(model_name, ref))
        if len(local_losses) < 2:
            pytest.fail("Not enough local RL steps")

        local_trend = local_losses[-1] - local_losses[0]

        print("\n=== RL Loss Direction ===")
        print(f"  Tinker trend: {ref_trend:+.4f}")
        print(f"  MLX trend:    {local_trend:+.4f}")

        min_len = min(len(ref_losses), len(local_losses))
        if abs(ref_trend) < 0.01 and abs(local_trend) < 0.01:
            max_abs_diff = np.max(np.abs(ref_losses[:min_len] - local_losses[:min_len]))
            assert max_abs_diff < 0.5, (
                f"Near-flat RL regime but max abs loss diff {max_abs_diff:.4f} > 0.5"
            )
        else:
            assert (ref_trend > 0) == (local_trend > 0), (
                f"RL trends differ: Tinker {ref_trend:+.4f} vs MLX {local_trend:+.4f}"
            )

    def _run_local_sft(self, model_name, ref, n_steps=None):
        """Run local SFT training matching the reference data.

        Replicates the exact text format from scripts/generate_reference_logs.py.
        """

        import tempfile

        from mlx_tinker.backend.mlx_backend import MLXBackend
        from mlx_tinker.config import EngineConfig
        from mlx_tinker.types import (
            AdamParams,
            CreateModelInput,
            Datum,
            EncodedTextChunk,
            ForwardBackwardInput,
            LoraConfig,
            LossFnInputs,
            ModelInput,
            OptimStepInput,
            TensorData,
        )

        wikisql_path = FIXTURES_DIR / "wikisql_subset.json"
        with open(wikisql_path) as f:
            wikisql_examples = json.load(f)

        config = EngineConfig(
            base_model=model_name,
            quantize_bits=4,
            quantize_group_size=64,
            checkpoints_base=tempfile.mkdtemp(),
        )
        backend = MLXBackend(config)
        lora_config = LoraConfig(
            rank=ref.get("lora_rank", 8),
            alpha=16.0,
            train_attn=True,
            train_mlp=True,
        )
        backend.create_model("equiv", CreateModelInput(lora_config=lora_config))
        tokenizer = backend.tokenizers["equiv"]

        steps = ref["sft_steps"][:n_steps] if n_steps else ref["sft_steps"]
        losses = []

        for step_idx, step_data in enumerate(steps):
            example = wikisql_examples[step_idx % len(wikisql_examples)]
            cols_str = " | ".join(example["columns"])
            prompt = f"Table: {cols_str}\nQuestion: {example['question']}\nSQL: "
            full_text = prompt + example["sql"]

            tokens = tokenizer.encode(full_text)[:256]
            input_tokens = tokens[:-1]
            target_tokens = tokens[1:]

            datum = Datum(
                model_input=ModelInput(chunks=[EncodedTextChunk(tokens=input_tokens)]),
                loss_fn_inputs=LossFnInputs(
                    target_tokens=TensorData(data=target_tokens),
                    weights=TensorData(data=[1.0] * len(target_tokens)),
                    advantages=TensorData(data=[0.0] * len(target_tokens)),
                    logprobs=TensorData(data=[0.0] * len(target_tokens)),
                ),
            )

            fb_result = backend.forward_backward(
                "equiv",
                ForwardBackwardInput(data=[datum], loss_fn="cross_entropy"),
            )
            losses.append(fb_result.metrics["loss:sum"] / max(len(target_tokens), 1))
            backend.optim_step(
                "equiv",
                OptimStepInput(adam_params=AdamParams(learning_rate=1e-4)),
            )

        return losses

    def _run_local_rl(self, model_name, ref):
        """Run local RL training matching the reference data.

        Replicates the exact text format and advantage structure from
        scripts/generate_reference_logs.py (cookbook pattern).
        """

        import tempfile

        from mlx_tinker.backend.mlx_backend import MLXBackend
        from mlx_tinker.config import EngineConfig
        from mlx_tinker.types import (
            AdamParams,
            CreateModelInput,
            Datum,
            EncodedTextChunk,
            ForwardBackwardInput,
            LoraConfig,
            LossFnInputs,
            ModelInput,
            OptimStepInput,
            TensorData,
        )

        wikisql_path = FIXTURES_DIR / "wikisql_subset.json"
        with open(wikisql_path) as f:
            wikisql_examples = json.load(f)

        config = EngineConfig(
            base_model=model_name,
            quantize_bits=4,
            quantize_group_size=64,
            checkpoints_base=tempfile.mkdtemp(),
        )
        backend = MLXBackend(config)
        lora_config = LoraConfig(
            rank=ref.get("lora_rank", 8), alpha=16.0, train_attn=True, train_mlp=True,
        )
        backend.create_model("equiv-rl", CreateModelInput(lora_config=lora_config))
        tokenizer = backend.tokenizers["equiv-rl"]

        steps = ref.get("rl_steps", [])
        losses = []

        for step_idx, step_data in enumerate(steps):
            example = wikisql_examples[step_idx % len(wikisql_examples)]
            cols_str = " | ".join(example["columns"])
            prompt = f"Table: {cols_str}\nQuestion: {example['question']}\nSQL: "
            full_text = prompt + example["sql"]

            tokens = tokenizer.encode(full_text)[:256]
            input_tokens = tokens[:-1]
            target_tokens = tokens[1:]

            prompt_tokens = tokenizer.encode(prompt)
            n_prompt = len(prompt_tokens) - 1
            n_tgt = len(target_tokens)

            weights = [0.0] * min(n_prompt, n_tgt)
            weights += [1.0] * max(0, n_tgt - n_prompt)
            weights = weights[:n_tgt]
            advantages = [0.0] * min(n_prompt, n_tgt)
            advantages += [1.0] * max(0, n_tgt - n_prompt)
            advantages = advantages[:n_tgt]

            datum = Datum(
                model_input=ModelInput(chunks=[EncodedTextChunk(tokens=input_tokens)]),
                loss_fn_inputs=LossFnInputs(
                    target_tokens=TensorData(data=target_tokens),
                    weights=TensorData(data=weights),
                    advantages=TensorData(data=advantages),
                    logprobs=TensorData(data=[0.0] * n_tgt),
                ),
            )

            fb_result = backend.forward_backward(
                "equiv-rl",
                ForwardBackwardInput(data=[datum], loss_fn="importance_sampling"),
            )
            losses.append(fb_result.metrics["loss:sum"] / max(n_tgt, 1))
            backend.optim_step(
                "equiv-rl",
                OptimStepInput(adam_params=AdamParams(learning_rate=5e-5)),
            )

        return losses
